# Generated by Django 4.1.3 on 2022-11-14 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_alter_ticketpassenger_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpassenger',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passengers',
            field=models.ManyToManyField(to='ticket.ticketpassenger'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
