# Generated by Django 4.1.3 on 2022-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticketpassenger_ticket_ticket_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('ticket_pass', 'ticket_pass'), ('ticket_single', 'ticket_single')], default='ticket_single', max_length=50),
        ),
    ]
