# Generated by Django 4.1.3 on 2022-11-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passengers',
            field=models.ManyToManyField(related_name='ticket_passengers', to='ticket.ticketpassenger'),
        ),
    ]
