# Generated by Django 4.1.3 on 2022-11-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passengers',
        ),
        migrations.AddField(
            model_name='ticketpassenger',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket'),
        ),
    ]
