# Generated by Django 4.1.3 on 2022-11-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_ticketpassenger_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_expiry_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.FloatField(),
        ),
    ]
