# Generated by Django 4.1.3 on 2022-11-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_ticketing_api', '0001_initial'),
        ('ticket', '0009_alter_payment_card_expiry_date_alter_ticket_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_ticketing_api.busschedule')),
                ('ticket_passenger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticketpassenger')),
            ],
            options={
                'verbose_name': 'Seating Plan',
                'verbose_name_plural': 'Seating Plans',
            },
        ),
    ]
